/**
 * PI Medical Summary Model
 * Represents AI-generated medical summary data
 */

export interface ProviderSummaryItem {
  providerName: string;
  providerType?: string;
  visitCount: number;
  totalBilled: number;
  firstVisit: string;
  lastVisit: string;
}

export interface DiagnosisItem {
  icd_code: string;
  description: string;
  primary?: boolean;
  firstDocumented?: string;
  provider?: string;
}

export interface RedFlagItem {
  description: string;
  severity: 'HIGH' | 'MEDIUM' | 'LOW';
}

export interface MissingRecordItem {
  type: string;
  reason: string;
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
}

export interface TreatmentGap {
  gapStart: string;
  gapEnd: string;
  gapDays: number;
  previousProvider: string;
  nextProvider: string;
  severity: 'HIGH' | 'MEDIUM';
}

/**
 * Tier 4 — phase-organized chronology entry. Generated by AI alongside the flat
 * treatmentChronology markdown table. Each phase groups one-or-more recordIds
 * into a clinical phase with a strategy-aware rationale paragraph.
 */
export interface ChronologyPhase {
  phase: string;            // "Acute", "Conservative treatment", etc.
  phaseRationale: string;   // 2-3 sentence rationale paragraph
  startDate?: string;       // ISO date
  endDate?: string;         // ISO date
  recordIds?: number[];     // PIMedicalRecord IDs in this phase
}

/**
 * Tier 5c — AI-detected open follow-up items the attorney should chase.
 */
export interface OpenItem {
  type: 'MISSING_IMAGING' | 'MISSING_CONSULT' | 'MISSING_PROCEDURE_NOTE'
      | 'MISSING_DISCHARGE' | 'MISSING_LAB' | 'MISSING_CLINICAL_NOTE' | 'OTHER';
  description: string;
  referencedIn?: string;
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
}

/**
 * P5.4 — Attorney-saved demand calculator scenario. Persists across sessions
 * via the demand_scenario JSONB column on pi_medical_summaries.
 */
export type FeeMode = 'PRE_SUIT_33' | 'SUIT_FILED_40';

export interface DemandScenario {
  /** P&S multiplier (typical attorney range 1.5×–5×, default 3.0×). */
  multiplier: number;
  /** Lost-wages dollar amount (separate from medical specials). */
  wageLoss: number;
  /** Attorney fee mode — 33⅓% pre-suit or 40% post-suit. */
  feeMode: FeeMode;
  /** Case costs (filing fees, expert reports, etc.). */
  costs: number;
  /** Total liens to satisfy from settlement. */
  liens: number;
  /** Server-stamped ISO timestamp of the most recent save. */
  savedAt?: string;
}

export interface PIMedicalSummary {
  id?: number;
  caseId: number;
  organizationId?: number;

  // Summary Content
  treatmentChronology?: string;
  phasedChronology?: ChronologyPhase[];
  providerSummary?: ProviderSummaryItem[];
  diagnosisList?: DiagnosisItem[];
  redFlags?: RedFlagItem[];
  missingRecords?: MissingRecordItem[];
  keyHighlights?: string;
  prognosisAssessment?: string;
  causationSummary?: string;          // Tier 5a — collated causation block
  openItems?: OpenItem[];             // Tier 5c — AI-detected follow-up items
  demandScenario?: DemandScenario;    // P5.4 — Attorney's last-saved demand calculator state

  // Metrics
  totalProviders?: number;
  totalVisits?: number;
  totalBilled?: number;
  treatmentDurationDays?: number;
  treatmentGapDays?: number;

  // Completeness Score
  completenessScore?: number;
  completenessNotes?: string;

  // Generation Info
  generatedAt?: string;
  generatedByModel?: string;
  lastRecordDate?: string;
  isStale?: boolean;

  // Related info
  caseNumber?: string;
  clientName?: string;
  injuryType?: string;

  // Metadata
  createdAt?: string;
  updatedAt?: string;
}

export interface CompletenessMetrics {
  completenessScore: number;
  completenessNotes: string;
  totalProviders: number;
  totalVisits: number;
  totalBilled: number;
  treatmentDurationDays: number;
  treatmentGapDays: number;
  isStale: boolean;
  lastGenerated: string;
}
