-- Create the two_factor_verifications table for MFA email verification codes
-- This table was missing from staging because it had no Flyway migration
-- (only existed via local Hibernate ddl-auto or manual setup)

CREATE TABLE IF NOT EXISTS two_factor_verifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    code            VARCHAR(10) NOT NULL,
    expiration_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_two_factor_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_two_factor_user_id ON two_factor_verifications(user_id);
CREATE INDEX IF NOT EXISTS idx_two_factor_code ON two_factor_verifications(code);
