-- Add calendar authorities to existing roles
-- For ROLE_USER: Add READ:CALENDAR and SYNC:CALENDAR
UPDATE ROLES 
SET permission = CONCAT(permission, ',READ:CALENDAR,SYNC:CALENDAR')
WHERE name = 'ROLE_USER';

-- For ROLE_MANAGER: Add READ:CALENDAR, CREATE:CALENDAR, UPDATE:CALENDAR, SYNC:CALENDAR
UPDATE ROLES 
SET permission = CONCAT(permission, ',READ:CALENDAR,CREATE:CALENDAR,UPDATE:CALENDAR,SYNC:CALENDAR')
WHERE name = 'ROLE_MANAGER';

-- For ROLE_ADMIN: Add READ:CALENDAR, CREATE:CALENDAR, UPDATE:CALENDAR, DELETE:CALENDAR, SYNC:CALENDAR
UPDATE ROLES 
SET permission = CONCAT(permission, ',READ:CALENDAR,CREATE:CALENDAR,UPDATE:CALENDAR,DELETE:CALENDAR,SYNC:CALENDAR')
WHERE name = 'ROLE_ADMIN';

-- For ROLE_SYSADMIN: Add READ:CALENDAR, CREATE:CALENDAR, UPDATE:CALENDAR, DELETE:CALENDAR, SYNC:CALENDAR
UPDATE ROLES 
SET permission = CONCAT(permission, ',READ:CALENDAR,CREATE:CALENDAR,UPDATE:CALENDAR,DELETE:CALENDAR,SYNC:CALENDAR')
WHERE name = 'ROLE_SYSADMIN'; 