-- ============================================================
-- V31: Comprehensive role permissions fix
-- All roles were missing critical permissions (CLIENT, TIME_TRACKING,
-- CALENDAR, BILLING, INVOICE, TASK, EXPENSE) causing "You don't have
-- permission" errors across the platform.
-- ============================================================

-- Expand permission column to hold full permission sets
ALTER TABLE roles ALTER COLUMN permission TYPE TEXT;

-- ── ROLE_ATTORNEY ──────────────────────────────────────────
-- Full case/client/doc/time/calendar/billing/invoice/task/expense access
UPDATE roles SET permission =
  'CASE:READ,CASE:CREATE,CASE:UPDATE,CASE:DELETE,CASE:VIEW,CASE:EDIT,CASE:ASSIGN,CASE:HISTORY,'
  || 'CLIENT:VIEW,CLIENT:CREATE,CLIENT:UPDATE,READ:CLIENT,UPDATE:CLIENT,'
  || 'DOCUMENT:VIEW,DOCUMENT:CREATE,DOCUMENT:EDIT,DOCUMENT:DELETE,DOCUMENT:SHARE,'
  || 'NOTE:READ,NOTE:CREATE,NOTE:UPDATE,NOTE:DELETE,'
  || 'TIME_TRACKING:VIEW,TIME_TRACKING:VIEW_OWN,TIME_TRACKING:CREATE,TIME_TRACKING:EDIT,TIME_TRACKING:UPDATE,TIME_TRACKING:DELETE,'
  || 'CALENDAR:VIEW,CALENDAR:CREATE,CALENDAR:EDIT,CALENDAR:DELETE,CREATE:CALENDAR,SYNC:CALENDAR,'
  || 'BILLING:VIEW,BILLING:EDIT,'
  || 'READ:INVOICE,CREATE:INVOICE,UPDATE:INVOICE,'
  || 'EXPENSE:VIEW,EXPENSE:CREATE,EXPENSE:UPDATE,EXPENSE:DELETE,'
  || 'TASK:VIEW_OWN,TASK:VIEW_TEAM,TASK:CREATE,TASK:EDIT,TASK:DELETE,TASK:COMMENT,TASK:ASSIGN,'
  || 'READ:PAYMENT_TRANSACTION,CREATE:PAYMENT_TRANSACTION,UPDATE:PAYMENT_TRANSACTION,'
  || 'reminders:read,reminders:create,reminders:update,reminders:delete,'
  || 'organization:read'
WHERE name = 'ROLE_ATTORNEY';

-- ── MANAGING_PARTNER / SENIOR_PARTNER / EQUITY_PARTNER ────
-- Same as attorney + admin-level billing, view all time, full invoice, task analytics
UPDATE roles SET permission =
  'CASE:READ,CASE:CREATE,CASE:UPDATE,CASE:DELETE,CASE:VIEW,CASE:EDIT,CASE:ASSIGN,CASE:HISTORY,CASE:ADMIN,CASE:TRANSFER,'
  || 'CLIENT:VIEW,CLIENT:CREATE,CLIENT:UPDATE,CLIENT:DELETE,READ:CLIENT,UPDATE:CLIENT,'
  || 'DOCUMENT:VIEW,DOCUMENT:CREATE,DOCUMENT:EDIT,DOCUMENT:DELETE,DOCUMENT:SHARE,DOCUMENT:RESTORE,'
  || 'NOTE:READ,NOTE:CREATE,NOTE:UPDATE,NOTE:DELETE,'
  || 'TIME_TRACKING:VIEW,TIME_TRACKING:VIEW_OWN,TIME_TRACKING:VIEW_ALL,TIME_TRACKING:VIEW_TEAM,TIME_TRACKING:CREATE,TIME_TRACKING:EDIT,TIME_TRACKING:UPDATE,TIME_TRACKING:DELETE,TIME_TRACKING:APPROVE,'
  || 'CALENDAR:VIEW,CALENDAR:CREATE,CALENDAR:EDIT,CALENDAR:DELETE,CREATE:CALENDAR,SYNC:CALENDAR,'
  || 'BILLING:VIEW,BILLING:EDIT,BILLING:ADMIN,'
  || 'READ:INVOICE,CREATE:INVOICE,UPDATE:INVOICE,DELETE:INVOICE,'
  || 'EXPENSE:VIEW,EXPENSE:CREATE,EXPENSE:UPDATE,EXPENSE:DELETE,'
  || 'TASK:VIEW_OWN,TASK:VIEW_TEAM,TASK:VIEW_ALL,TASK:CREATE,TASK:EDIT,TASK:DELETE,TASK:COMMENT,TASK:ASSIGN,TASK:ADMIN,TASK:ANALYTICS,'
  || 'READ:PAYMENT_TRANSACTION,CREATE:PAYMENT_TRANSACTION,UPDATE:PAYMENT_TRANSACTION,'
  || 'ADMINISTRATIVE:VIEW,'
  || 'reminders:read,reminders:create,reminders:update,reminders:delete,'
  || 'organization:read,organization:update,'
  || 'transfer:read,transfer:approve,workload:read,workload:analytics'
WHERE name IN ('MANAGING_PARTNER', 'SENIOR_PARTNER', 'EQUITY_PARTNER');

-- ── ASSOCIATE / SENIOR_ASSOCIATE / JUNIOR_ASSOCIATE / OF_COUNSEL / NON_EQUITY_PARTNER ──
-- Same as attorney (full practitioner access)
UPDATE roles SET permission =
  'CASE:READ,CASE:CREATE,CASE:UPDATE,CASE:DELETE,CASE:VIEW,CASE:EDIT,CASE:ASSIGN,CASE:HISTORY,'
  || 'CLIENT:VIEW,CLIENT:CREATE,CLIENT:UPDATE,READ:CLIENT,UPDATE:CLIENT,'
  || 'DOCUMENT:VIEW,DOCUMENT:CREATE,DOCUMENT:EDIT,DOCUMENT:DELETE,DOCUMENT:SHARE,'
  || 'NOTE:READ,NOTE:CREATE,NOTE:UPDATE,NOTE:DELETE,'
  || 'TIME_TRACKING:VIEW,TIME_TRACKING:VIEW_OWN,TIME_TRACKING:CREATE,TIME_TRACKING:EDIT,TIME_TRACKING:UPDATE,TIME_TRACKING:DELETE,'
  || 'CALENDAR:VIEW,CALENDAR:CREATE,CALENDAR:EDIT,CALENDAR:DELETE,CREATE:CALENDAR,SYNC:CALENDAR,'
  || 'BILLING:VIEW,BILLING:EDIT,'
  || 'READ:INVOICE,CREATE:INVOICE,UPDATE:INVOICE,'
  || 'EXPENSE:VIEW,EXPENSE:CREATE,EXPENSE:UPDATE,EXPENSE:DELETE,'
  || 'TASK:VIEW_OWN,TASK:VIEW_TEAM,TASK:CREATE,TASK:EDIT,TASK:DELETE,TASK:COMMENT,TASK:ASSIGN,'
  || 'READ:PAYMENT_TRANSACTION,CREATE:PAYMENT_TRANSACTION,UPDATE:PAYMENT_TRANSACTION,'
  || 'reminders:read,reminders:create,reminders:update,reminders:delete,'
  || 'organization:read'
WHERE name IN ('ASSOCIATE', 'SENIOR_ASSOCIATE', 'JUNIOR_ASSOCIATE', 'OF_COUNSEL', 'NON_EQUITY_PARTNER');

-- ── ROLE_PARALEGAL / SENIOR_PARALEGAL / LEGAL_ASSISTANT / LAW_CLERK ──
-- Case support, client view, docs, notes, own time, calendar, tasks
UPDATE roles SET permission =
  'CASE:READ,CASE:CREATE,CASE:UPDATE,CASE:VIEW,CASE:EDIT,CASE:HISTORY,'
  || 'CLIENT:VIEW,READ:CLIENT,'
  || 'DOCUMENT:VIEW,DOCUMENT:CREATE,DOCUMENT:EDIT,DOCUMENT:SHARE,'
  || 'NOTE:READ,NOTE:CREATE,NOTE:UPDATE,'
  || 'TIME_TRACKING:VIEW,TIME_TRACKING:VIEW_OWN,TIME_TRACKING:CREATE,TIME_TRACKING:EDIT,TIME_TRACKING:UPDATE,'
  || 'CALENDAR:VIEW,CALENDAR:CREATE,CALENDAR:EDIT,CREATE:CALENDAR,'
  || 'BILLING:VIEW,'
  || 'READ:INVOICE,'
  || 'EXPENSE:VIEW,EXPENSE:CREATE,'
  || 'TASK:VIEW_OWN,TASK:VIEW_TEAM,TASK:CREATE,TASK:EDIT,TASK:COMMENT,'
  || 'reminders:read,reminders:create,reminders:update,'
  || 'organization:read'
WHERE name IN ('PARALEGAL', 'SENIOR_PARALEGAL', 'LEGAL_ASSISTANT', 'LAW_CLERK');

-- ── ROLE_SECRETARY ─────────────────────────────────────────
-- Calendar management, basic case/client view, tasks, documents
UPDATE roles SET permission =
  'CASE:READ,CASE:VIEW,CASE:HISTORY,'
  || 'CLIENT:VIEW,READ:CLIENT,'
  || 'DOCUMENT:VIEW,DOCUMENT:CREATE,'
  || 'NOTE:READ,NOTE:CREATE,'
  || 'CALENDAR:VIEW,CALENDAR:CREATE,CALENDAR:EDIT,CALENDAR:DELETE,CREATE:CALENDAR,SYNC:CALENDAR,'
  || 'BILLING:VIEW,'
  || 'READ:INVOICE,'
  || 'TASK:VIEW_OWN,TASK:CREATE,TASK:EDIT,TASK:COMMENT,'
  || 'reminders:read,reminders:create,reminders:update,'
  || 'organization:read'
WHERE name = 'ROLE_SECRETARY';

-- ── ROLE_ADMIN ─────────────────────────────────────────────
-- Full access to everything (also passes via hasRole fallback, but explicit is safer)
UPDATE roles SET permission =
  'CASE:READ,CASE:CREATE,CASE:UPDATE,CASE:DELETE,CASE:VIEW,CASE:EDIT,CASE:ASSIGN,CASE:ADMIN,CASE:HISTORY,CASE:TRANSFER,'
  || 'CLIENT:VIEW,CLIENT:CREATE,CLIENT:UPDATE,CLIENT:DELETE,READ:CLIENT,UPDATE:CLIENT,'
  || 'DOCUMENT:VIEW,DOCUMENT:CREATE,DOCUMENT:EDIT,DOCUMENT:DELETE,DOCUMENT:SHARE,DOCUMENT:RESTORE,DOCUMENT:PERMANENT_DELETE,'
  || 'NOTE:READ,NOTE:CREATE,NOTE:UPDATE,NOTE:DELETE,'
  || 'TIME_TRACKING:VIEW,TIME_TRACKING:VIEW_OWN,TIME_TRACKING:VIEW_ALL,TIME_TRACKING:VIEW_TEAM,TIME_TRACKING:CREATE,TIME_TRACKING:EDIT,TIME_TRACKING:UPDATE,TIME_TRACKING:DELETE,TIME_TRACKING:APPROVE,'
  || 'CALENDAR:VIEW,CALENDAR:CREATE,CALENDAR:EDIT,CALENDAR:DELETE,CREATE:CALENDAR,SYNC:CALENDAR,'
  || 'BILLING:VIEW,BILLING:EDIT,BILLING:ADMIN,'
  || 'READ:INVOICE,CREATE:INVOICE,UPDATE:INVOICE,DELETE:INVOICE,'
  || 'EXPENSE:VIEW,EXPENSE:CREATE,EXPENSE:UPDATE,EXPENSE:DELETE,'
  || 'TASK:VIEW_OWN,TASK:VIEW_TEAM,TASK:VIEW_ALL,TASK:CREATE,TASK:EDIT,TASK:DELETE,TASK:COMMENT,TASK:ASSIGN,TASK:ADMIN,TASK:ANALYTICS,'
  || 'READ:PAYMENT_TRANSACTION,CREATE:PAYMENT_TRANSACTION,UPDATE:PAYMENT_TRANSACTION,'
  || 'USER:READ,USER:CREATE,USER:UPDATE,USER:DELETE,USER:VIEW,'
  || 'ROLE:READ,ROLE:CREATE,ROLE:UPDATE,ROLE:DELETE,ROLE:VIEW,ROLE:ADMIN,ROLE:ASSIGN,'
  || 'ADMINISTRATIVE:VIEW,ADMINISTRATIVE:ADMIN,ADMINISTRATIVE:CREATE,'
  || 'ORGANIZATION:VIEW,organization:read,organization:update,'
  || 'reminders:read,reminders:create,reminders:update,reminders:delete,'
  || 'rules:read,rules:create,rules:update,'
  || 'transfer:read,transfer:approve,workload:read,workload:analytics,'
  || 'MANAGER:VIEW,MANAGER:CREATE,MANAGER:EDIT,'
  || 'legal_research:admin'
WHERE name = 'ROLE_ADMIN';

-- ── ROLE_SUPERADMIN ────────────────────────────────────────
-- Same as ROLE_ADMIN (also has superadmin-only endpoints via hasRole)
UPDATE roles SET permission = (SELECT permission FROM roles WHERE name = 'ROLE_ADMIN' LIMIT 1)
WHERE name = 'ROLE_SUPERADMIN';

-- ── ROLE_USER ──────────────────────────────────────────────
-- Basic platform access
UPDATE roles SET permission =
  'CASE:READ,CASE:VIEW,'
  || 'CLIENT:VIEW,READ:CLIENT,'
  || 'DOCUMENT:VIEW,'
  || 'NOTE:READ,'
  || 'TIME_TRACKING:VIEW_OWN,TIME_TRACKING:CREATE,'
  || 'CALENDAR:VIEW,CALENDAR:CREATE,'
  || 'BILLING:VIEW,'
  || 'READ:INVOICE,'
  || 'TASK:VIEW_OWN,TASK:CREATE,TASK:COMMENT,'
  || 'organization:read'
WHERE name = 'ROLE_USER';

-- ── Financial roles (CFO, FINANCE_MANAGER, ROLE_FINANCE) ──
UPDATE roles SET permission =
  'CLIENT:VIEW,READ:CLIENT,'
  || 'CASE:READ,CASE:VIEW,'
  || 'BILLING:VIEW,BILLING:EDIT,BILLING:ADMIN,'
  || 'READ:INVOICE,CREATE:INVOICE,UPDATE:INVOICE,DELETE:INVOICE,'
  || 'EXPENSE:VIEW,EXPENSE:CREATE,EXPENSE:UPDATE,EXPENSE:DELETE,'
  || 'TIME_TRACKING:VIEW,TIME_TRACKING:VIEW_ALL,TIME_TRACKING:APPROVE,'
  || 'READ:PAYMENT_TRANSACTION,CREATE:PAYMENT_TRANSACTION,UPDATE:PAYMENT_TRANSACTION,'
  || 'ADMINISTRATIVE:VIEW,'
  || 'TASK:VIEW_OWN,TASK:CREATE,TASK:COMMENT,'
  || 'organization:read'
WHERE name IN ('CFO', 'FINANCE_MANAGER', 'ROLE_FINANCE');

-- ── Operations roles (COO, PRACTICE_MANAGER) ──
UPDATE roles SET permission =
  'CASE:READ,CASE:VIEW,CASE:HISTORY,'
  || 'CLIENT:VIEW,READ:CLIENT,'
  || 'DOCUMENT:VIEW,'
  || 'BILLING:VIEW,BILLING:EDIT,'
  || 'READ:INVOICE,'
  || 'EXPENSE:VIEW,'
  || 'TIME_TRACKING:VIEW,TIME_TRACKING:VIEW_ALL,TIME_TRACKING:VIEW_TEAM,'
  || 'TASK:VIEW_OWN,TASK:VIEW_TEAM,TASK:VIEW_ALL,TASK:CREATE,TASK:EDIT,TASK:COMMENT,TASK:ASSIGN,TASK:ANALYTICS,'
  || 'CALENDAR:VIEW,CALENDAR:CREATE,CALENDAR:EDIT,'
  || 'ADMINISTRATIVE:VIEW,'
  || 'workload:read,workload:analytics,'
  || 'organization:read'
WHERE name IN ('COO', 'PRACTICE_MANAGER');

-- ── IT / HR roles ──
UPDATE roles SET permission =
  'USER:READ,USER:CREATE,USER:UPDATE,USER:VIEW,'
  || 'ROLE:VIEW,'
  || 'ADMINISTRATIVE:VIEW,'
  || 'TASK:VIEW_OWN,TASK:CREATE,TASK:COMMENT,'
  || 'organization:read'
WHERE name IN ('IT_MANAGER', 'HR_MANAGER');

-- ── ROLE_CLIENT ────────────────────────────────────────────
-- Client portal only — no org-level permissions needed
-- (Leave empty — portal uses its own hasRole('ROLE_CLIENT') checks)
