-- Add new AI/platform entity types to audit_log CHECK constraint
ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_entity_type_check;
ALTER TABLE audit_log ADD CONSTRAINT audit_log_entity_type_check CHECK (entity_type::text = ANY(ARRAY[
  'CUSTOMER','CASE','LEGAL_CASE','DOCUMENT','INVOICE','USER',
  'APPOINTMENT','PAYMENT','EXPENSE','ROLE','PERMISSION','EMAIL',
  'CALENDAR_EVENT','ORGANIZATION','INVITATION','CLIENT','TASK','NOTE',
  'ANALYTICS','SYSTEM','SECURITY','ANNOUNCEMENT','INTEGRATION','AUDIT_LOG','PLATFORM',
  'MEDICAL_RECORD','MEDICAL_SUMMARY','CONFLICT_CHECK','LEAD',
  'AI_WORKSPACE','LEGAL_RESEARCH','DEMAND_LETTER','DOCUMENT_ANALYSIS','AI_BRIEFING','FILE_MANAGER',
  'BILLING_RATE','EXPENSE_CATEGORY'
]::text[]));
