-- ============================================================
-- V42: Seed remaining state court configurations
-- Adds DEFAULT court configs for all 42 remaining US states + DC
-- that were not seeded in V41.
-- All marked is_verified = FALSE pending attorney review.
-- ============================================================

-- ── ALABAMA ─────────────────────────────────────────────────
INSERT INTO state_court_configurations (
    state_code, state_name, court_level, court_display_name,
    caption_template_html, caption_separator, cause_number_label,
    is_commonwealth, party_label_style, comes_now_format, prayer_format,
    bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs,
    priority_rank, is_active, is_verified
) VALUES (
    'AL', 'Alabama', 'DEFAULT', 'IN THE CIRCUIT COURT',
    '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>',
    '', 'Civil Action No.', FALSE, 'STANDARD',
    'COMES NOW the {partyRole}, {partyName}, by and through undersigned counsel, and respectfully moves this Honorable Court to {relief}, and in support thereof states:',
    'WHEREFORE, the {partyRole} respectfully requests that this Honorable Court:',
    'ASB No.', '["So. 3d", "So. 2d", "Ala.", "Ala. Civ. App."]',
    '{"civil": "Ala. R. Civ. P.", "criminal": "Ala. R. Crim. P.", "evidence": "Ala. R. Evid."}',
    '{"state": "Ala. Const. art. I", "federal": "U.S. Const. amend."}',
    20, TRUE, FALSE
);

-- ── ALASKA ──────────────────────────────────────────────────
INSERT INTO state_court_configurations (
    state_code, state_name, court_level, court_display_name,
    caption_template_html, caption_separator, cause_number_label,
    is_commonwealth, party_label_style, comes_now_format, prayer_format,
    bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs,
    priority_rank, is_active, is_verified
) VALUES (
    'AK', 'Alaska', 'DEFAULT', 'IN THE SUPERIOR COURT FOR THE STATE OF ALASKA',
    '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>',
    '', 'Case No.', FALSE, 'STANDARD',
    '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:',
    'WHEREFORE, {partyRole} respectfully requests that this Court:',
    'Bar No.', '["P.3d", "P.2d", "Alaska"]',
    '{"civil": "Alaska R. Civ. P.", "criminal": "Alaska R. Crim. P.", "evidence": "Alaska R. Evid."}',
    '{"state": "Alaska Const. art. I", "federal": "U.S. Const. amend."}',
    30, TRUE, FALSE
);

-- ── ARIZONA ─────────────────────────────────────────────────
INSERT INTO state_court_configurations (
    state_code, state_name, court_level, court_display_name,
    caption_template_html, caption_separator, cause_number_label,
    is_commonwealth, party_label_style, comes_now_format, prayer_format,
    bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs,
    priority_rank, is_active, is_verified
) VALUES (
    'AZ', 'Arizona', 'DEFAULT', 'IN THE SUPERIOR COURT OF THE STATE OF ARIZONA',
    '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>IN AND FOR THE COUNTY OF {{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>',
    '', 'Case No.', FALSE, 'STANDARD',
    '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:',
    'WHEREFORE, {partyRole} respectfully requests that this Court:',
    'SBN', '["P.3d", "P.2d", "Ariz.", "Ariz. App."]',
    '{"civil": "Ariz. R. Civ. P.", "criminal": "Ariz. R. Crim. P.", "evidence": "Ariz. R. Evid."}',
    '{"state": "Ariz. Const. art. 2", "federal": "U.S. Const. amend."}',
    20, TRUE, FALSE
);

-- ── ARKANSAS ────────────────────────────────────────────────
INSERT INTO state_court_configurations (
    state_code, state_name, court_level, court_display_name,
    caption_template_html, caption_separator, cause_number_label,
    is_commonwealth, party_label_style, comes_now_format, prayer_format,
    bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs,
    priority_rank, is_active, is_verified
) VALUES (
    'AR', 'Arkansas', 'DEFAULT', 'IN THE CIRCUIT COURT',
    '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>',
    '', 'Case No.', FALSE, 'STANDARD',
    'COMES NOW the {partyRole}, {partyName}, by and through undersigned counsel, and respectfully moves this Court to {relief}, and states:',
    'WHEREFORE, the {partyRole} respectfully requests that this Court:',
    'Bar No.', '["S.W.3d", "S.W.2d", "Ark.", "Ark. App."]',
    '{"civil": "Ark. R. Civ. P.", "criminal": "Ark. R. Crim. P.", "evidence": "Ark. R. Evid."}',
    '{"state": "Ark. Const. art. 2", "federal": "U.S. Const. amend."}',
    30, TRUE, FALSE
);

-- ── COLORADO ────────────────────────────────────────────────
INSERT INTO state_court_configurations (
    state_code, state_name, court_level, court_display_name,
    caption_template_html, caption_separator, cause_number_label,
    is_commonwealth, party_label_style, comes_now_format, prayer_format,
    bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs,
    priority_rank, is_active, is_verified
) VALUES (
    'CO', 'Colorado', 'DEFAULT', 'DISTRICT COURT',
    '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>',
    '§', 'Case No.', FALSE, 'PEOPLE',
    '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:',
    'WHEREFORE, {partyRole} respectfully requests that this Court:',
    'Atty. Reg. No.', '["P.3d", "P.2d", "Colo.", "Colo. App."]',
    '{"civil": "C.R.C.P.", "criminal": "Colo. R. Crim. P.", "evidence": "C.R.E."}',
    '{"state": "Colo. Const. art. II", "federal": "U.S. Const. amend."}',
    20, TRUE, FALSE
);

-- ── CONNECTICUT ─────────────────────────────────────────────
INSERT INTO state_court_configurations (
    state_code, state_name, court_level, court_display_name,
    caption_template_html, caption_separator, cause_number_label,
    is_commonwealth, party_label_style, comes_now_format, prayer_format,
    bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs,
    priority_rank, is_active, is_verified
) VALUES (
    'CT', 'Connecticut', 'DEFAULT', 'SUPERIOR COURT',
    '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>JUDICIAL DISTRICT OF {{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>',
    '', 'Docket No.', FALSE, 'STANDARD',
    'The {partyRole}, {partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:',
    'WHEREFORE, the {partyRole} respectfully requests that this Court:',
    'Juris No.', '["A.3d", "A.2d", "Conn.", "Conn. App.", "Conn. Supp."]',
    '{"civil": "Conn. Practice Book", "criminal": "Conn. Practice Book", "evidence": "Conn. Code of Evid."}',
    '{"state": "Conn. Const. art. first", "federal": "U.S. Const. amend."}',
    25, TRUE, FALSE
);

-- ── DELAWARE ────────────────────────────────────────────────
INSERT INTO state_court_configurations (
    state_code, state_name, court_level, court_display_name,
    caption_template_html, caption_separator, cause_number_label,
    is_commonwealth, party_label_style, comes_now_format, prayer_format,
    bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs,
    priority_rank, is_active, is_verified
) VALUES (
    'DE', 'Delaware', 'DEFAULT', 'IN THE SUPERIOR COURT OF THE STATE OF DELAWARE',
    '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>',
    '', 'C.A. No.', FALSE, 'STANDARD',
    '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:',
    'WHEREFORE, {partyRole} respectfully requests that this Court:',
    'Bar I.D. No.', '["A.3d", "A.2d", "Del.", "Del. Ch.", "Del. Super."]',
    '{"civil": "Del. Super. Ct. Civ. R.", "criminal": "Del. Super. Ct. Crim. R.", "evidence": "D.R.E."}',
    '{"state": "Del. Const. art. I", "federal": "U.S. Const. amend."}',
    25, TRUE, FALSE
);

-- ── DISTRICT OF COLUMBIA ────────────────────────────────────
INSERT INTO state_court_configurations (
    state_code, state_name, court_level, court_display_name,
    caption_template_html, caption_separator, cause_number_label,
    is_commonwealth, party_label_style, comes_now_format, prayer_format,
    bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs,
    priority_rank, is_active, is_verified
) VALUES (
    'DC', 'District of Columbia', 'DEFAULT', 'SUPERIOR COURT OF THE DISTRICT OF COLUMBIA',
    '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>CIVIL DIVISION</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>',
    '', 'Case No.', FALSE, 'STANDARD',
    '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:',
    'WHEREFORE, {partyRole} respectfully requests that this Court:',
    'Bar No.', '["A.3d", "A.2d"]',
    '{"civil": "D.C. Super. Ct. Civ. R.", "criminal": "D.C. Super. Ct. Crim. R.", "evidence": "D.C. Super. Ct. Civ. R."}',
    '{"federal": "U.S. Const. amend."}',
    15, TRUE, FALSE
);

-- ── GEORGIA ─────────────────────────────────────────────────
INSERT INTO state_court_configurations (
    state_code, state_name, court_level, court_display_name,
    caption_template_html, caption_separator, cause_number_label,
    is_commonwealth, party_label_style, comes_now_format, prayer_format,
    bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs,
    priority_rank, is_active, is_verified
) VALUES (
    'GA', 'Georgia', 'DEFAULT', 'IN THE SUPERIOR COURT',
    '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>',
    '', 'Civil Action File No.', FALSE, 'STANDARD',
    'COMES NOW the {partyRole}, {partyName}, by and through undersigned counsel, and respectfully shows this Court as follows:',
    'WHEREFORE, the {partyRole} respectfully prays that this Court:',
    'Ga. Bar No.', '["S.E.2d", "Ga.", "Ga. App."]',
    '{"civil": "O.C.G.A.", "criminal": "O.C.G.A.", "evidence": "O.C.G.A. Title 24"}',
    '{"state": "Ga. Const. art. I", "federal": "U.S. Const. amend."}',
    10, TRUE, FALSE
);

-- ── HAWAII ──────────────────────────────────────────────────
INSERT INTO state_court_configurations (
    state_code, state_name, court_level, court_display_name,
    caption_template_html, caption_separator, cause_number_label,
    is_commonwealth, party_label_style, comes_now_format, prayer_format,
    bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs,
    priority_rank, is_active, is_verified
) VALUES (
    'HI', 'Hawaii', 'DEFAULT', 'IN THE CIRCUIT COURT OF THE FIRST CIRCUIT',
    '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>STATE OF HAWAII</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">vs.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>',
    '', 'Civil No.', FALSE, 'STANDARD',
    '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:',
    'WHEREFORE, {partyRole} respectfully requests that this Court:',
    'Bar No.', '["P.3d", "P.2d", "Haw.", "Haw. App."]',
    '{"civil": "Haw. R. Civ. P.", "criminal": "Haw. R. Penal P.", "evidence": "Haw. R. Evid."}',
    '{"state": "Haw. Const. art. I", "federal": "U.S. Const. amend."}',
    30, TRUE, FALSE
);

-- ── IDAHO ───────────────────────────────────────────────────
INSERT INTO state_court_configurations (state_code, state_name, court_level, court_display_name, caption_template_html, caption_separator, cause_number_label, is_commonwealth, party_label_style, comes_now_format, prayer_format, bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs, priority_rank, is_active, is_verified)
VALUES ('ID', 'Idaho', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'ISB No.', '["P.3d", "P.2d", "Idaho"]', '{"civil": "I.R.C.P.", "criminal": "I.C.R.", "evidence": "I.R.E."}', '{"state": "Idaho Const. art. I", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE);

-- ── INDIANA ─────────────────────────────────────────────────
INSERT INTO state_court_configurations (state_code, state_name, court_level, court_display_name, caption_template_html, caption_separator, cause_number_label, is_commonwealth, party_label_style, comes_now_format, prayer_format, bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs, priority_rank, is_active, is_verified)
VALUES ('IN', 'Indiana', 'DEFAULT', 'IN THE CIRCUIT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Cause No.', FALSE, 'STANDARD', 'COMES NOW the {partyRole}, {partyName}, by counsel, and respectfully moves this Court to {relief}, and in support states:', 'WHEREFORE, the {partyRole} respectfully requests that this Court:', 'Atty. No.', '["N.E.3d", "N.E.2d", "Ind.", "Ind. App."]', '{"civil": "Ind. R. Trial P.", "criminal": "Ind. R. Crim. P.", "evidence": "Ind. R. Evid."}', '{"state": "Ind. Const. art. 1", "federal": "U.S. Const. amend."}', 20, TRUE, FALSE);

-- ── IOWA ────────────────────────────────────────────────────
INSERT INTO state_court_configurations (state_code, state_name, court_level, court_display_name, caption_template_html, caption_separator, cause_number_label, is_commonwealth, party_label_style, comes_now_format, prayer_format, bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs, priority_rank, is_active, is_verified)
VALUES ('IA', 'Iowa', 'DEFAULT', 'IN THE IOWA DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', 'COMES NOW the {partyRole}, {partyName}, by and through undersigned counsel, and respectfully moves this Court to {relief}, and states:', 'WHEREFORE, the {partyRole} respectfully requests that this Court:', 'AT No.', '["N.W.2d", "Iowa"]', '{"civil": "Iowa R. Civ. P.", "criminal": "Iowa R. Crim. P.", "evidence": "Iowa R. Evid."}', '{"state": "Iowa Const. art. I", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE);

-- ── KANSAS ──────────────────────────────────────────────────
INSERT INTO state_court_configurations (state_code, state_name, court_level, court_display_name, caption_template_html, caption_separator, cause_number_label, is_commonwealth, party_label_style, comes_now_format, prayer_format, bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs, priority_rank, is_active, is_verified)
VALUES ('KS', 'Kansas', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', 'COMES NOW the {partyRole}, {partyName}, by and through undersigned counsel, and respectfully moves this Court to {relief}:', 'WHEREFORE, the {partyRole} respectfully requests that this Court:', 'KS Bar No.', '["P.3d", "P.2d", "Kan.", "Kan. App. 2d"]', '{"civil": "K.S.A.", "criminal": "K.S.A.", "evidence": "K.S.A. ch. 60, art. 4"}', '{"state": "Kan. Const. Bill of Rights", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE);

-- ── KENTUCKY ────────────────────────────────────────────────
INSERT INTO state_court_configurations (state_code, state_name, court_level, court_display_name, caption_template_html, caption_separator, cause_number_label, is_commonwealth, party_label_style, comes_now_format, prayer_format, bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs, priority_rank, is_active, is_verified)
VALUES ('KY', 'Kentucky', 'DEFAULT', 'IN THE CIRCUIT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Civil Action No.', TRUE, 'COMMONWEALTH', 'COMES NOW the {partyRole}, {partyName}, by counsel, and respectfully moves this Court to {relief}, and states:', 'WHEREFORE, the {partyRole} respectfully requests that this Court:', 'KBA No.', '["S.W.3d", "S.W.2d", "Ky.", "Ky. App."]', '{"civil": "Ky. R. Civ. P.", "criminal": "Ky. R. Crim. P.", "evidence": "Ky. R. Evid."}', '{"state": "Ky. Const.", "federal": "U.S. Const. amend."}', 20, TRUE, FALSE);

-- ── LOUISIANA ───────────────────────────────────────────────
INSERT INTO state_court_configurations (state_code, state_name, court_level, court_display_name, caption_template_html, caption_separator, cause_number_label, is_commonwealth, party_label_style, comes_now_format, prayer_format, bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs, priority_rank, is_active, is_verified)
VALUES ('LA', 'Louisiana', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>PARISH OF {{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">VERSUS</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Docket No.', FALSE, 'STANDARD', 'NOW INTO COURT, through undersigned counsel, comes {partyName}, who respectfully moves this Honorable Court for {relief}, and represents:', 'WHEREFORE, mover prays that this Honorable Court:', 'La. Bar Roll No.', '["So. 3d", "So. 2d", "La.", "La. App."]', '{"civil": "La. Code Civ. Proc.", "criminal": "La. Code Crim. Proc.", "evidence": "La. Code Evid."}', '{"state": "La. Const. art. I", "federal": "U.S. Const. amend."}', 15, TRUE, FALSE);

-- ── MAINE ───────────────────────────────────────────────────
INSERT INTO state_court_configurations (state_code, state_name, court_level, court_display_name, caption_template_html, caption_separator, cause_number_label, is_commonwealth, party_label_style, comes_now_format, prayer_format, bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs, priority_rank, is_active, is_verified)
VALUES ('ME', 'Maine', 'DEFAULT', 'SUPERIOR COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>STATE OF MAINE</strong><br/><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Docket No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Bar No.', '["A.3d", "A.2d", "Me."]', '{"civil": "Me. R. Civ. P.", "criminal": "Me. R. Crim. P.", "evidence": "Me. R. Evid."}', '{"state": "Me. Const. art. I", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE);

-- ── MARYLAND ────────────────────────────────────────────────
INSERT INTO state_court_configurations (state_code, state_name, court_level, court_display_name, caption_template_html, caption_separator, cause_number_label, is_commonwealth, party_label_style, comes_now_format, prayer_format, bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs, priority_rank, is_active, is_verified)
VALUES ('MD', 'Maryland', 'DEFAULT', 'IN THE CIRCUIT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>FOR {{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Bar No.', '["A.3d", "A.2d", "Md.", "Md. App."]', '{"civil": "Md. Rule", "criminal": "Md. Rule", "evidence": "Md. Rule 5"}', '{"state": "Md. Const. Decl. of Rights", "federal": "U.S. Const. amend."}', 15, TRUE, FALSE);

-- Remaining states: MI, MN, MS, MO, MT, NE, NV, NH, NJ, NM, NC, ND, OH, OK, OR, RI, SC, SD, TN, UT, VT, VA, WA, WV, WI, WY
-- Using compact INSERT format with the standard default caption template

INSERT INTO state_court_configurations (state_code, state_name, court_level, court_display_name, caption_template_html, caption_separator, cause_number_label, is_commonwealth, party_label_style, comes_now_format, prayer_format, bar_number_prefix, citation_reporters, procedural_rules_ref, constitutional_refs, priority_rank, is_active, is_verified)
VALUES
('MI', 'Michigan', 'DEFAULT', 'IN THE CIRCUIT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'PEOPLE', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'P No.', '["N.W.2d", "Mich.", "Mich. App."]', '{"civil": "MCR", "criminal": "MCR", "evidence": "MRE"}', '{"state": "Mich. Const. art. 1", "federal": "U.S. Const. amend."}', 15, TRUE, FALSE),

('MN', 'Minnesota', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>STATE OF MINNESOTA</strong><br/><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">vs.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Court File No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Atty. Reg. No.', '["N.W.2d", "Minn.", "Minn. App."]', '{"civil": "Minn. R. Civ. P.", "criminal": "Minn. R. Crim. P.", "evidence": "Minn. R. Evid."}', '{"state": "Minn. Const. art. I", "federal": "U.S. Const. amend."}', 20, TRUE, FALSE),

('MS', 'Mississippi', 'DEFAULT', 'IN THE CIRCUIT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Civil Action No.', FALSE, 'STANDARD', 'COMES NOW the {partyRole}, {partyName}, by and through undersigned counsel, and respectfully moves this Court to {relief}:', 'WHEREFORE, the {partyRole} respectfully requests that this Court:', 'MSB No.', '["So. 3d", "So. 2d", "Miss."]', '{"civil": "Miss. R. Civ. P.", "criminal": "Miss. R. Crim. P. (URCCC)", "evidence": "Miss. R. Evid."}', '{"state": "Miss. Const. art. 3", "federal": "U.S. Const. amend."}', 25, TRUE, FALSE),

('MO', 'Missouri', 'DEFAULT', 'IN THE CIRCUIT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Cause No.', FALSE, 'STANDARD', 'COMES NOW {partyName}, by and through undersigned counsel, and for {partyName}''s motion states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Mo. Bar No.', '["S.W.3d", "S.W.2d", "Mo.", "Mo. App."]', '{"civil": "Mo. R. Civ. P.", "criminal": "Mo. R. Crim. P.", "evidence": "Mo. Stat."}', '{"state": "Mo. Const. art. I", "federal": "U.S. Const. amend."}', 20, TRUE, FALSE),

('MT', 'Montana', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">vs.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Cause No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Bar No.', '["P.3d", "P.2d", "Mont."]', '{"civil": "Mont. R. Civ. P.", "criminal": "Mont. Code Ann.", "evidence": "Mont. R. Evid."}', '{"state": "Mont. Const. art. II", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE),

('NE', 'Nebraska', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', 'COMES NOW the {partyRole}, {partyName}, by and through undersigned counsel, and moves this Court for {relief}, and states:', 'WHEREFORE, the {partyRole} respectfully requests this Court:', 'NSBA No.', '["N.W.2d", "Neb.", "Neb. App."]', '{"civil": "Neb. Ct. R.", "criminal": "Neb. Ct. R.", "evidence": "Neb. Evid. R."}', '{"state": "Neb. Const. art. I", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE),

('NV', 'Nevada', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">vs.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Nev. Bar No.', '["P.3d", "P.2d", "Nev."]', '{"civil": "NRCP", "criminal": "NRS", "evidence": "NRS ch. 48-52"}', '{"state": "Nev. Const. art. 1", "federal": "U.S. Const. amend."}', 20, TRUE, FALSE),

('NH', 'New Hampshire', 'DEFAULT', 'SUPERIOR COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>STATE OF NEW HAMPSHIRE</strong><br/><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'NHBA No.', '["A.3d", "A.2d", "N.H."]', '{"civil": "N.H. R. Civ. P. Super. Ct.", "criminal": "N.H. R. Crim. P.", "evidence": "N.H. R. Evid."}', '{"state": "N.H. Const. pt. 1, art.", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE),

('NJ', 'New Jersey', 'DEFAULT', 'SUPERIOR COURT OF NEW JERSEY', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>LAW DIVISION, {{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Docket No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and certifies:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Attorney I.D. No.', '["A.3d", "A.2d", "N.J.", "N.J. Super."]', '{"civil": "N.J. Ct. R.", "criminal": "N.J. Ct. R.", "evidence": "N.J.R.E."}', '{"state": "N.J. Const. art. I", "federal": "U.S. Const. amend."}', 10, TRUE, FALSE),

('NM', 'New Mexico', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Cause No.', FALSE, 'STANDARD', 'COMES NOW the {partyRole}, {partyName}, by and through undersigned counsel, and moves this Court to {relief}, and states:', 'WHEREFORE, the {partyRole} respectfully requests that this Court:', 'Bar No.', '["P.3d", "P.2d", "N.M."]', '{"civil": "N.M. R. Civ. P. Dist. Ct.", "criminal": "N.M. R. Crim. P. Dist. Ct.", "evidence": "N.M. R. Evid."}', '{"state": "N.M. Const. art. II", "federal": "U.S. Const. amend."}', 25, TRUE, FALSE),

('NC', 'North Carolina', 'DEFAULT', 'IN THE GENERAL COURT OF JUSTICE, SUPERIOR COURT DIVISION', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>STATE OF NORTH CAROLINA</strong><br/><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'File No.', FALSE, 'STANDARD', 'NOW COMES the {partyRole}, {partyName}, by and through undersigned counsel, and respectfully moves this Court to {relief}, and shows:', 'WHEREFORE, the {partyRole} respectfully requests that this Court:', 'State Bar No.', '["S.E.2d", "N.C.", "N.C. App."]', '{"civil": "N.C. R. Civ. P.", "criminal": "N.C. Gen. Stat.", "evidence": "N.C. R. Evid."}', '{"state": "N.C. Const. art. I", "federal": "U.S. Const. amend."}', 15, TRUE, FALSE),

('ND', 'North Dakota', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'ID No.', '["N.W.2d", "N.D."]', '{"civil": "N.D.R.Civ.P.", "criminal": "N.D.R.Crim.P.", "evidence": "N.D.R.Ev."}', '{"state": "N.D. Const. art. I", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE),

('OH', 'Ohio', 'DEFAULT', 'IN THE COURT OF COMMON PLEAS', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', 'NOW COMES {partyName}, by and through undersigned counsel, and respectfully moves this Court to {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Ohio Sup. Ct. Reg. No.', '["N.E.3d", "N.E.2d", "Ohio St. 3d", "Ohio App. 3d"]', '{"civil": "Ohio Civ. R.", "criminal": "Ohio Crim. R.", "evidence": "Ohio Evid. R."}', '{"state": "Ohio Const. art. I", "federal": "U.S. Const. amend."}', 10, TRUE, FALSE),

('OK', 'Oklahoma', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', 'COMES NOW the {partyRole}, {partyName}, and respectfully moves this Court to {relief}, and states:', 'WHEREFORE, the {partyRole} respectfully requests that this Court:', 'OBA No.', '["P.3d", "P.2d", "Okla.", "Okla. Crim."]', '{"civil": "Okla. Stat. tit. 12", "criminal": "Okla. Stat. tit. 22", "evidence": "Okla. Stat. tit. 12, ch. 40"}', '{"state": "Okla. Const. art. II", "federal": "U.S. Const. amend."}', 20, TRUE, FALSE),

('OR', 'Oregon', 'DEFAULT', 'IN THE CIRCUIT COURT OF THE STATE OF OREGON', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>FOR THE COUNTY OF {{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'OSB No.', '["P.3d", "P.2d", "Or.", "Or. App."]', '{"civil": "ORCP", "criminal": "ORS ch. 135-138", "evidence": "OEC"}', '{"state": "Or. Const. art. I", "federal": "U.S. Const. amend."}', 20, TRUE, FALSE),

('RI', 'Rhode Island', 'DEFAULT', 'SUPERIOR COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>STATE OF RHODE ISLAND</strong><br/><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'C.A. No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Bar No.', '["A.3d", "A.2d", "R.I."]', '{"civil": "R.I. Super. R. Civ. P.", "criminal": "R.I. Super. R. Crim. P.", "evidence": "R.I. R. Evid."}', '{"state": "R.I. Const. art. I", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE),

('SC', 'South Carolina', 'DEFAULT', 'IN THE COURT OF COMMON PLEAS', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>STATE OF SOUTH CAROLINA</strong><br/><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', 'COMES NOW the {partyRole}, {partyName}, by and through undersigned counsel, and respectfully moves this Court to {relief}, and would show:', 'WHEREFORE, the {partyRole} respectfully prays that this Court:', 'SC Bar No.', '["S.E.2d", "S.C.", "S.C. App. (unpublished)"]', '{"civil": "S.C.R.C.P.", "criminal": "S.C.R.Crim.P.", "evidence": "S.C.R.E."}', '{"state": "S.C. Const. art. I", "federal": "U.S. Const. amend."}', 20, TRUE, FALSE),

('SD', 'South Dakota', 'DEFAULT', 'IN THE CIRCUIT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Civ. No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Bar No.', '["N.W.2d", "S.D."]', '{"civil": "SDCL ch. 15-6", "criminal": "SDCL ch. 23A", "evidence": "SDCL ch. 19-19"}', '{"state": "S.D. Const. art. VI", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE),

('TN', 'Tennessee', 'DEFAULT', 'IN THE CIRCUIT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', 'COMES NOW the {partyRole}, {partyName}, by and through undersigned counsel, and respectfully moves this Court to {relief}, and states:', 'WHEREFORE, the {partyRole} respectfully requests that this Honorable Court:', 'BPR No.', '["S.W.3d", "S.W.2d", "Tenn.", "Tenn. App."]', '{"civil": "Tenn. R. Civ. P.", "criminal": "Tenn. R. Crim. P.", "evidence": "Tenn. R. Evid."}', '{"state": "Tenn. Const. art. I", "federal": "U.S. Const. amend."}', 15, TRUE, FALSE),

('UT', 'Utah', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Bar No.', '["P.3d", "P.2d", "Utah", "Utah App. (unpublished)"]', '{"civil": "Utah R. Civ. P.", "criminal": "Utah R. Crim. P.", "evidence": "Utah R. Evid."}', '{"state": "Utah Const. art. I", "federal": "U.S. Const. amend."}', 20, TRUE, FALSE),

('VT', 'Vermont', 'DEFAULT', 'SUPERIOR COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>STATE OF VERMONT</strong><br/><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Docket No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Bar No.', '["A.3d", "A.2d", "Vt."]', '{"civil": "V.R.C.P.", "criminal": "V.R.Cr.P.", "evidence": "V.R.E."}', '{"state": "Vt. Const. ch. I", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE),

('VA', 'Virginia', 'DEFAULT', 'IN THE CIRCUIT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', TRUE, 'COMMONWEALTH', 'COMES NOW the {partyRole}, {partyName}, by counsel, and moves this Court to {relief}, and states:', 'WHEREFORE, the {partyRole} respectfully requests that this Court:', 'VSB No.', '["S.E.2d", "Va.", "Va. App."]', '{"civil": "Va. Sup. Ct. R.", "criminal": "Va. Sup. Ct. R.", "evidence": "Va. Sup. Ct. R. 2:"}', '{"state": "Va. Const. art. I", "federal": "U.S. Const. amend."}', 10, TRUE, FALSE),

('WA', 'Washington', 'DEFAULT', 'IN THE SUPERIOR COURT OF THE STATE OF WASHINGTON', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>IN AND FOR THE COUNTY OF {{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Cause No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'WSBA No.', '["P.3d", "P.2d", "Wn.2d", "Wn. App.", "Wn. App. 2d"]', '{"civil": "Wash. CR", "criminal": "Wash. CrR", "evidence": "Wash. ER"}', '{"state": "Wash. Const. art. I", "federal": "U.S. Const. amend."}', 15, TRUE, FALSE),

('WV', 'West Virginia', 'DEFAULT', 'IN THE CIRCUIT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Civil Action No.', FALSE, 'STANDARD', 'COMES NOW the {partyRole}, {partyName}, by counsel, and respectfully moves this Court to {relief}, and states:', 'WHEREFORE, the {partyRole} respectfully requests that this Court:', 'WVSB No.', '["S.E.2d", "W. Va."]', '{"civil": "W. Va. R. Civ. P.", "criminal": "W. Va. R. Crim. P.", "evidence": "W. Va. R. Evid."}', '{"state": "W. Va. Const. art. III", "federal": "U.S. Const. amend."}', 25, TRUE, FALSE),

('WI', 'Wisconsin', 'DEFAULT', 'IN THE CIRCUIT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>STATE OF WISCONSIN</strong><br/><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Case No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'State Bar No.', '["N.W.2d", "Wis. 2d", "Wis. App. (unpublished)"]', '{"civil": "Wis. Stat. ch. 801-847", "criminal": "Wis. Stat. ch. 967-979", "evidence": "Wis. Stat. ch. 901-911"}', '{"state": "Wis. Const. art. I", "federal": "U.S. Const. amend."}', 20, TRUE, FALSE),

('WY', 'Wyoming', 'DEFAULT', 'IN THE DISTRICT COURT', '<div align="center" style="text-align:center; margin-bottom:8px;"><strong>{{courtName}}</strong><br/><span>{{countyState}}</span></div><div align="center" style="text-align:center; margin-bottom:12px;"><strong>{{causeNumberLabel}} {{caseNumber}}</strong></div><table width="85%" align="center" border="0" cellpadding="4" cellspacing="0" style="width:85%; margin-left:auto; margin-right:auto; border:none; border-collapse:collapse;"><tr><td width="45%" valign="top" style="border:none; padding:2px 4px;">{{plaintiffName}},</td><td width="10%" style="border:none;"></td><td width="45%" style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{plaintiffLabel}},</em></td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:8px 4px;">v.</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td valign="top" style="border:none; padding:2px 4px;">{{defendantName}},</td><td style="border:none;"></td><td style="border:none;"></td></tr><tr><td style="border:none; padding:2px 4px; padding-left:24px;"><em>{{defendantLabel}}.</em></td><td style="border:none;"></td><td style="border:none;"></td></tr></table>', '', 'Civil No.', FALSE, 'STANDARD', '{partyName}, by and through undersigned counsel, respectfully moves this Court for {relief}, and states:', 'WHEREFORE, {partyRole} respectfully requests that this Court:', 'Wyo. State Bar No.', '["P.3d", "P.2d", "Wyo."]', '{"civil": "W.R.C.P.", "criminal": "W.R.Cr.P.", "evidence": "W.R.E."}', '{"state": "Wyo. Const. art. 1", "federal": "U.S. Const. amend."}', 30, TRUE, FALSE);
