import {
  FolderOpen, CalendarCheck, Timer, ListTodo, Brain, FileText, PenTool,
  ScanSearch, PenLine, UserCheck, BookUser, PieChart, Stethoscope, Scale,
  User, Users, Building, Newspaper, ShieldCheck, Plug, FileCheck2, Send,
  ChevronDown, X, Menu, Lock, Shield, ClipboardList, Phone, Mail, Globe,
  Rocket, Lightbulb, Bot, Search, Calculator, CircleDollarSign, DollarSign,
  Hospital, Car, Gavel, Landmark, BarChart3, TrendingUp, Cloud, Key, Eye,
  RefreshCw, Gift, AlarmClock, AlertTriangle, Link2, LayoutDashboard,
  Folder, File, Paperclip, CheckCircle, Trash2, Upload, CreditCard, Tag,
  MessageSquare, Monitor, Smartphone, BookOpen, Frown, Flashlight, Target,
  Wrench, Unlock, ShieldAlert, Calendar, ArrowRight, Sparkles, Check,
  ChevronRight, Star, Zap, Heart, Clock, MapPin, ExternalLink, Info,
  Settings, Database, FileCode, Layers, BarChart2, History
} from "lucide-react"

const MAP = {
  "ri-folders-line": FolderOpen,
  "ri-calendar-check-line": CalendarCheck,
  "ri-timer-line": Timer,
  "ri-task-line": ListTodo,
  "ri-brain-line": Brain,
  "ri-file-text-line": FileText,
  "ri-draft-line": PenTool,
  "ri-search-eye-line": ScanSearch,
  "ri-quill-pen-line": PenLine,
  "ri-user-heart-line": UserCheck,
  "ri-contacts-book-line": BookUser,
  "ri-pie-chart-line": PieChart,
  "ri-stethoscope-line": Stethoscope,
  "ri-scales-3-line": Scale,
  "ri-user-line": User,
  "ri-group-line": Users,
  "ri-building-line": Building,
  "ri-article-line": Newspaper,
  "ri-shield-check-line": ShieldCheck,
  "ri-plug-line": Plug,
  "ri-file-shield-2-line": FileCheck2,
  "ri-team-line": Users,
  "ri-mail-send-line": Send,
  "ri-arrow-down-s-line": ChevronDown,
  "ri-close-line": X,
  "ri-menu-line": Menu,
  "ri-lock-line": Lock,
  "ri-shield-line": Shield,
  "ri-clipboard-line": ClipboardList,
  "ri-phone-line": Phone,
  "ri-mail-line": Mail,
  "ri-globe-line": Globe,
  "ri-rocket-line": Rocket,
  "ri-lightbulb-line": Lightbulb,
  "ri-robot-line": Bot,
  "ri-search-line": Search,
  "ri-calculator-line": Calculator,
  "ri-money-dollar-circle-line": CircleDollarSign,
  "ri-money-dollar-box-line": DollarSign,
  "ri-hospital-line": Hospital,
  "ri-car-line": Car,
  "ri-hammer-line": Gavel,
  "ri-government-line": Landmark,
  "ri-bar-chart-box-line": BarChart3,
  "ri-line-chart-line": TrendingUp,
  "ri-cloud-line": Cloud,
  "ri-key-line": Key,
  "ri-eye-line": Eye,
  "ri-refresh-line": RefreshCw,
  "ri-gift-line": Gift,
  "ri-alarm-line": AlarmClock,
  "ri-alert-line": AlertTriangle,
  "ri-link": Link2,
  "ri-dashboard-3-line": LayoutDashboard,
  "ri-folder-line": Folder,
  "ri-folder-open-line": FolderOpen,
  "ri-file-line": File,
  "ri-attachment-line": Paperclip,
  "ri-checkbox-circle-line": CheckCircle,
  "ri-delete-bin-line": Trash2,
  "ri-upload-line": Upload,
  "ri-bank-card-line": CreditCard,
  "ri-price-tag-3-line": Tag,
  "ri-chat-3-line": MessageSquare,
  "ri-computer-line": Monitor,
  "ri-smartphone-line": Smartphone,
  "ri-book-open-line": BookOpen,
  "ri-emotion-unhappy-line": Frown,
  "ri-flashlight-line": Flashlight,
  "ri-focus-3-line": Target,
  "ri-tools-line": Wrench,
  "ri-lock-unlock-line": Unlock,
  "ri-shield-keyhole-line": ShieldAlert,
  "ri-calendar-line": Calendar,
  "ri-history-line": History,
}

/**
 * Universal icon component replacing Remix Icons with Lucide React.
 * Usage: <Icon name="ri-brain-line" size={16} /> or <Icon name="ri-brain-line" className="..." />
 */
export default function Icon({ name, size = 16, className = "", style = {}, ...props }) {
  const Comp = MAP[name]
  if (!Comp) return <span className={className} style={{ width: size, height: size, display: "inline-flex", ...style }} {...props} />
  return <Comp size={size} className={className} style={style} strokeWidth={1.8} {...props} />
}

// Re-export individual icons for direct use
export {
  FolderOpen, CalendarCheck, Timer, ListTodo, Brain, FileText, PenTool,
  ScanSearch, PenLine, UserCheck, BookUser, PieChart, Stethoscope, Scale,
  User, Users, Building, Newspaper, ShieldCheck, Plug, FileCheck2, Send,
  ChevronDown, X, Menu, Lock, Shield, ClipboardList, Phone, Mail, Globe,
  Rocket, Lightbulb, Bot, Search, Calculator, CircleDollarSign, DollarSign,
  Hospital, Car, Gavel, Landmark, BarChart3, TrendingUp, Cloud, Key, Eye,
  RefreshCw, Gift, AlarmClock, AlertTriangle, Link2, LayoutDashboard,
  Folder, File, Paperclip, CheckCircle, Trash2, Upload, CreditCard, Tag,
  MessageSquare, Monitor, Smartphone, BookOpen, Frown, Flashlight, Target,
  Wrench, Unlock, ShieldAlert, Calendar, ArrowRight, Sparkles, Check,
  ChevronRight, Star, Zap, Heart, Clock, MapPin, ExternalLink, Info,
  Settings, Database, FileCode, Layers, BarChart2, History
}
