-- Clean up existing WORKFLOW_SUGGESTION notifications
-- These were generated by WorkflowNotificationScheduler which is now disabled
DELETE FROM public.user_notifications WHERE type = 'WORKFLOW_SUGGESTION';
