-- Appointment Requests Table
-- Tracks client appointment requests and their status

CREATE TABLE IF NOT EXISTS appointment_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    calendar_event_id BIGINT UNSIGNED COMMENT 'Links to calendar_events once confirmed',
    case_id BIGINT UNSIGNED,
    client_id BIGINT UNSIGNED NOT NULL,
    attorney_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    appointment_type VARCHAR(50) NOT NULL COMMENT 'CONSULTATION, MEETING, FOLLOW_UP, etc.',
    preferred_datetime DATETIME NOT NULL,
    alternative_datetime DATETIME,
    duration_minutes INT NOT NULL DEFAULT 30,
    is_virtual BOOLEAN NOT NULL DEFAULT FALSE,
    meeting_link VARCHAR(500),
    location VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, CONFIRMED, RESCHEDULED, CANCELLED, COMPLETED',
    notes TEXT COMMENT 'Client notes',
    attorney_notes TEXT COMMENT 'Attorney response notes',
    confirmed_datetime DATETIME COMMENT 'Final confirmed time',
    cancelled_by VARCHAR(50) COMMENT 'CLIENT or ATTORNEY',
    cancellation_reason TEXT,
    reminder_sent BOOLEAN NOT NULL DEFAULT FALSE,
    reminder_24h_sent BOOLEAN NOT NULL DEFAULT FALSE,
    reminder_1h_sent BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_appointment_requests_client (client_id),
    KEY idx_appointment_requests_attorney (attorney_id),
    KEY idx_appointment_requests_case (case_id),
    KEY idx_appointment_requests_status (status),
    KEY idx_appointment_requests_datetime (preferred_datetime),
    CONSTRAINT fk_appointment_requests_calendar FOREIGN KEY (calendar_event_id) REFERENCES calendar_events(id) ON DELETE SET NULL,
    CONSTRAINT fk_appointment_requests_case FOREIGN KEY (case_id) REFERENCES legal_cases(id) ON DELETE SET NULL,
    CONSTRAINT fk_appointment_requests_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_requests_attorney FOREIGN KEY (attorney_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
