package com.bostoneo.bostoneosolutions.enumeration;

public enum FeatureType {
    DOCUMENT_GENERATION,
    LEGAL_RESEARCH,
    CONTRACT_ANALYSIS,
    IMMIGRATION_ASSISTANCE,
    FAMILY_LAW_CALCULATION,
    CRIMINAL_ANALYSIS,
    REAL_ESTATE_ASSISTANCE,
    PATENT_ANALYSIS,
    COLLABORATION,
    TEMPLATE_USAGE,
    AI_SUGGESTIONS
}